services:
  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    environment:
      WORDPRESS_DB_HOST: dbserver
      WORDPRESS_DB_USER_FILE: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: db
      WORDPRESS_TABLE_PREFIX: wp_1
    ports:
      - "${WORDPRESS1_PORT}:80"
    networks:
      - appnet
    depends_on:
      - dbserver
    secrets:
      - db_user
      - db_password

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    environment:
      WORDPRESS_DB_HOST: dbserver
      WORDPRESS_DB_USER_FILE: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: db
      WORDPRESS_TABLE_PREFIX: wp_2
    ports:
      - "${WORDPRESS2_PORT}:80"
    networks:
      - appnet
    depends_on:
      - dbserver
    secrets:
      - db_user
      - db_password

  dbserver:
    image: docker.io/library/mysql:5.7
    container_name: dbserver
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: db
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet
    secrets:
      - db_root_password
      - db_user
      - db_password

secrets:
  db_root_password:
    external: true
  db_user:
    external: true
  db_password:
    external: true

networks:
  appnet: {}

volumes:
  dbdata: {}
