services:
  wordpress1:
    image: docker.io/library/wordpress:latest
    container_name: wordpress1
    environment:
      WORDPRESS_DB_HOST: 127.0.0.1
      WORDPRESS_DB_PORT: 3307
      WORDPRESS_DB_USER_FILE: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: db
      WORDPRESS_TABLE_PREFIX: wp_1
    ports:
      - "${WORDPRESS1_PORT}:80"
    networks:
      - appnet
    depends_on:
      - dbserver
    secrets:
      - db_user
      - db_password

  wordpress2:
    image: docker.io/library/wordpress:latest
    container_name: wordpress2
    environment:
      WORDPRESS_DB_HOST: 127.0.0.1
      WORDPRESS_DB_PORT: 3307
      WORDPRESS_DB_USER_FILE: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: db
      WORDPRESS_TABLE_PREFIX: wp_2
    ports:
      - "${WORDPRESS2_PORT}:80"
    networks:
      - appnet
    depends_on:
      - dbserver
    secrets:
      - db_user
      - db_password

  mysql-proxy:
    image: docker.io/library/nginx:latest
    container_name: mysql-proxy
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3307:3307"
    restart: always

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_root_password:
    external: true

networks:
  appnet: {}